// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `relay/datatransfer.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18relay/datatransfer.proto\x12\x12relay.datatransfer\x1a\x10common/a\
    ck.proto\x1a\x12common/state.proto\x1a\x12common/query.proto2\xc2\x01\n\
    \x0cDataTransfer\x126\n\x0cRequestState\x12\x13.common.query.Query\x1a\
    \x0f.common.ack.Ack\"\0\x129\n\tSendState\x12\x19.common.state.ViewPaylo\
    ad\x1a\x0f.common.ack.Ack\"\0\x12?\n\x0fSendDriverState\x12\x19.common.s\
    tate.ViewPayload\x1a\x0f.common.ack.Ack\"\0Bv\n$com.weaver.protos.relay.\
    datatransferZNgithub.com/hyperledger-labs/weaver-dlt-interoperability/co\
    mmon/protos-go/relayb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
