// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `networks/networks.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct DbName {
    // message fields
    pub name: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DbName {
    fn default() -> &'a DbName {
        <DbName as ::protobuf::Message>::default_instance()
    }
}

impl DbName {
    pub fn new() -> DbName {
        ::std::default::Default::default()
    }

    // string name = 1;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }
}

impl ::protobuf::Message for DbName {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DbName {
        DbName::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &DbName| { &m.name },
                |m: &mut DbName| { &mut m.name },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<DbName>(
                "DbName",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static DbName {
        static instance: ::protobuf::rt::LazyV2<DbName> = ::protobuf::rt::LazyV2::INIT;
        instance.get(DbName::new)
    }
}

impl ::protobuf::Clear for DbName {
    fn clear(&mut self) {
        self.name.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DbName {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DbName {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RelayDatabase {
    // message fields
    pub pairs: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RelayDatabase {
    fn default() -> &'a RelayDatabase {
        <RelayDatabase as ::protobuf::Message>::default_instance()
    }
}

impl RelayDatabase {
    pub fn new() -> RelayDatabase {
        ::std::default::Default::default()
    }

    // repeated .networks.networks.RelayDatabase.PairsEntry pairs = 1;


    pub fn get_pairs(&self) -> &::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &self.pairs
    }
    pub fn clear_pairs(&mut self) {
        self.pairs.clear();
    }

    // Param is passed by value, moved
    pub fn set_pairs(&mut self, v: ::std::collections::HashMap<::std::string::String, ::std::string::String>) {
        self.pairs = v;
    }

    // Mutable pointer to the field.
    pub fn mut_pairs(&mut self) -> &mut ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &mut self.pairs
    }

    // Take field
    pub fn take_pairs(&mut self) -> ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        ::std::mem::replace(&mut self.pairs, ::std::collections::HashMap::new())
    }
}

impl ::protobuf::Message for RelayDatabase {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(wire_type, is, &mut self.pairs)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(1, &self.pairs);
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(1, &self.pairs, os)?;
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RelayDatabase {
        RelayDatabase::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(
                "pairs",
                |m: &RelayDatabase| { &m.pairs },
                |m: &mut RelayDatabase| { &mut m.pairs },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RelayDatabase>(
                "RelayDatabase",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RelayDatabase {
        static instance: ::protobuf::rt::LazyV2<RelayDatabase> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RelayDatabase::new)
    }
}

impl ::protobuf::Clear for RelayDatabase {
    fn clear(&mut self) {
        self.pairs.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RelayDatabase {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RelayDatabase {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct GetStateMessage {
    // message fields
    pub request_id: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a GetStateMessage {
    fn default() -> &'a GetStateMessage {
        <GetStateMessage as ::protobuf::Message>::default_instance()
    }
}

impl GetStateMessage {
    pub fn new() -> GetStateMessage {
        ::std::default::Default::default()
    }

    // string request_id = 1;


    pub fn get_request_id(&self) -> &str {
        &self.request_id
    }
    pub fn clear_request_id(&mut self) {
        self.request_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_request_id(&mut self, v: ::std::string::String) {
        self.request_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_request_id(&mut self) -> &mut ::std::string::String {
        &mut self.request_id
    }

    // Take field
    pub fn take_request_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.request_id, ::std::string::String::new())
    }
}

impl ::protobuf::Message for GetStateMessage {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.request_id)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.request_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.request_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.request_id.is_empty() {
            os.write_string(1, &self.request_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> GetStateMessage {
        GetStateMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "request_id",
                |m: &GetStateMessage| { &m.request_id },
                |m: &mut GetStateMessage| { &mut m.request_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<GetStateMessage>(
                "GetStateMessage",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static GetStateMessage {
        static instance: ::protobuf::rt::LazyV2<GetStateMessage> = ::protobuf::rt::LazyV2::INIT;
        instance.get(GetStateMessage::new)
    }
}

impl ::protobuf::Clear for GetStateMessage {
    fn clear(&mut self) {
        self.request_id.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for GetStateMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetStateMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct NetworkQuery {
    // message fields
    pub policy: ::protobuf::RepeatedField<::std::string::String>,
    pub address: ::std::string::String,
    pub requesting_relay: ::std::string::String,
    pub requesting_network: ::std::string::String,
    pub certificate: ::std::string::String,
    pub requestor_signature: ::std::string::String,
    pub nonce: ::std::string::String,
    pub requesting_org: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a NetworkQuery {
    fn default() -> &'a NetworkQuery {
        <NetworkQuery as ::protobuf::Message>::default_instance()
    }
}

impl NetworkQuery {
    pub fn new() -> NetworkQuery {
        ::std::default::Default::default()
    }

    // repeated string policy = 1;


    pub fn get_policy(&self) -> &[::std::string::String] {
        &self.policy
    }
    pub fn clear_policy(&mut self) {
        self.policy.clear();
    }

    // Param is passed by value, moved
    pub fn set_policy(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.policy = v;
    }

    // Mutable pointer to the field.
    pub fn mut_policy(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.policy
    }

    // Take field
    pub fn take_policy(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.policy, ::protobuf::RepeatedField::new())
    }

    // string address = 2;


    pub fn get_address(&self) -> &str {
        &self.address
    }
    pub fn clear_address(&mut self) {
        self.address.clear();
    }

    // Param is passed by value, moved
    pub fn set_address(&mut self, v: ::std::string::String) {
        self.address = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address(&mut self) -> &mut ::std::string::String {
        &mut self.address
    }

    // Take field
    pub fn take_address(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.address, ::std::string::String::new())
    }

    // string requesting_relay = 3;


    pub fn get_requesting_relay(&self) -> &str {
        &self.requesting_relay
    }
    pub fn clear_requesting_relay(&mut self) {
        self.requesting_relay.clear();
    }

    // Param is passed by value, moved
    pub fn set_requesting_relay(&mut self, v: ::std::string::String) {
        self.requesting_relay = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_requesting_relay(&mut self) -> &mut ::std::string::String {
        &mut self.requesting_relay
    }

    // Take field
    pub fn take_requesting_relay(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.requesting_relay, ::std::string::String::new())
    }

    // string requesting_network = 4;


    pub fn get_requesting_network(&self) -> &str {
        &self.requesting_network
    }
    pub fn clear_requesting_network(&mut self) {
        self.requesting_network.clear();
    }

    // Param is passed by value, moved
    pub fn set_requesting_network(&mut self, v: ::std::string::String) {
        self.requesting_network = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_requesting_network(&mut self) -> &mut ::std::string::String {
        &mut self.requesting_network
    }

    // Take field
    pub fn take_requesting_network(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.requesting_network, ::std::string::String::new())
    }

    // string certificate = 5;


    pub fn get_certificate(&self) -> &str {
        &self.certificate
    }
    pub fn clear_certificate(&mut self) {
        self.certificate.clear();
    }

    // Param is passed by value, moved
    pub fn set_certificate(&mut self, v: ::std::string::String) {
        self.certificate = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_certificate(&mut self) -> &mut ::std::string::String {
        &mut self.certificate
    }

    // Take field
    pub fn take_certificate(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.certificate, ::std::string::String::new())
    }

    // string requestor_signature = 6;


    pub fn get_requestor_signature(&self) -> &str {
        &self.requestor_signature
    }
    pub fn clear_requestor_signature(&mut self) {
        self.requestor_signature.clear();
    }

    // Param is passed by value, moved
    pub fn set_requestor_signature(&mut self, v: ::std::string::String) {
        self.requestor_signature = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_requestor_signature(&mut self) -> &mut ::std::string::String {
        &mut self.requestor_signature
    }

    // Take field
    pub fn take_requestor_signature(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.requestor_signature, ::std::string::String::new())
    }

    // string nonce = 7;


    pub fn get_nonce(&self) -> &str {
        &self.nonce
    }
    pub fn clear_nonce(&mut self) {
        self.nonce.clear();
    }

    // Param is passed by value, moved
    pub fn set_nonce(&mut self, v: ::std::string::String) {
        self.nonce = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nonce(&mut self) -> &mut ::std::string::String {
        &mut self.nonce
    }

    // Take field
    pub fn take_nonce(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.nonce, ::std::string::String::new())
    }

    // string requesting_org = 8;


    pub fn get_requesting_org(&self) -> &str {
        &self.requesting_org
    }
    pub fn clear_requesting_org(&mut self) {
        self.requesting_org.clear();
    }

    // Param is passed by value, moved
    pub fn set_requesting_org(&mut self, v: ::std::string::String) {
        self.requesting_org = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_requesting_org(&mut self) -> &mut ::std::string::String {
        &mut self.requesting_org
    }

    // Take field
    pub fn take_requesting_org(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.requesting_org, ::std::string::String::new())
    }
}

impl ::protobuf::Message for NetworkQuery {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.policy)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.address)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.requesting_relay)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.requesting_network)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.certificate)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.requestor_signature)?;
                },
                7 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.nonce)?;
                },
                8 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.requesting_org)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.policy {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.address);
        }
        if !self.requesting_relay.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.requesting_relay);
        }
        if !self.requesting_network.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.requesting_network);
        }
        if !self.certificate.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.certificate);
        }
        if !self.requestor_signature.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.requestor_signature);
        }
        if !self.nonce.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.nonce);
        }
        if !self.requesting_org.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.requesting_org);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.policy {
            os.write_string(1, &v)?;
        };
        if !self.address.is_empty() {
            os.write_string(2, &self.address)?;
        }
        if !self.requesting_relay.is_empty() {
            os.write_string(3, &self.requesting_relay)?;
        }
        if !self.requesting_network.is_empty() {
            os.write_string(4, &self.requesting_network)?;
        }
        if !self.certificate.is_empty() {
            os.write_string(5, &self.certificate)?;
        }
        if !self.requestor_signature.is_empty() {
            os.write_string(6, &self.requestor_signature)?;
        }
        if !self.nonce.is_empty() {
            os.write_string(7, &self.nonce)?;
        }
        if !self.requesting_org.is_empty() {
            os.write_string(8, &self.requesting_org)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> NetworkQuery {
        NetworkQuery::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "policy",
                |m: &NetworkQuery| { &m.policy },
                |m: &mut NetworkQuery| { &mut m.policy },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "address",
                |m: &NetworkQuery| { &m.address },
                |m: &mut NetworkQuery| { &mut m.address },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "requesting_relay",
                |m: &NetworkQuery| { &m.requesting_relay },
                |m: &mut NetworkQuery| { &mut m.requesting_relay },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "requesting_network",
                |m: &NetworkQuery| { &m.requesting_network },
                |m: &mut NetworkQuery| { &mut m.requesting_network },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "certificate",
                |m: &NetworkQuery| { &m.certificate },
                |m: &mut NetworkQuery| { &mut m.certificate },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "requestor_signature",
                |m: &NetworkQuery| { &m.requestor_signature },
                |m: &mut NetworkQuery| { &mut m.requestor_signature },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "nonce",
                |m: &NetworkQuery| { &m.nonce },
                |m: &mut NetworkQuery| { &mut m.nonce },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "requesting_org",
                |m: &NetworkQuery| { &m.requesting_org },
                |m: &mut NetworkQuery| { &mut m.requesting_org },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<NetworkQuery>(
                "NetworkQuery",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static NetworkQuery {
        static instance: ::protobuf::rt::LazyV2<NetworkQuery> = ::protobuf::rt::LazyV2::INIT;
        instance.get(NetworkQuery::new)
    }
}

impl ::protobuf::Clear for NetworkQuery {
    fn clear(&mut self) {
        self.policy.clear();
        self.address.clear();
        self.requesting_relay.clear();
        self.requesting_network.clear();
        self.certificate.clear();
        self.requestor_signature.clear();
        self.nonce.clear();
        self.requesting_org.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for NetworkQuery {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NetworkQuery {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17networks/networks.proto\x12\x11networks.networks\x1a\x10common/ack\
    .proto\x1a\x12common/state.proto\"\x1c\n\x06DbName\x12\x12\n\x04name\x18\
    \x01\x20\x01(\tR\x04name\"\x8c\x01\n\rRelayDatabase\x12A\n\x05pairs\x18\
    \x01\x20\x03(\x0b2+.networks.networks.RelayDatabase.PairsEntryR\x05pairs\
    \x1a8\n\nPairsEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\
    \n\x05value\x18\x02\x20\x01(\tR\x05value:\x028\x01\"0\n\x0fGetStateMessa\
    ge\x12\x1d\n\nrequest_id\x18\x01\x20\x01(\tR\trequestId\"\xaa\x02\n\x0cN\
    etworkQuery\x12\x16\n\x06policy\x18\x01\x20\x03(\tR\x06policy\x12\x18\n\
    \x07address\x18\x02\x20\x01(\tR\x07address\x12)\n\x10requesting_relay\
    \x18\x03\x20\x01(\tR\x0frequestingRelay\x12-\n\x12requesting_network\x18\
    \x04\x20\x01(\tR\x11requestingNetwork\x12\x20\n\x0bcertificate\x18\x05\
    \x20\x01(\tR\x0bcertificate\x12/\n\x13requestor_signature\x18\x06\x20\
    \x01(\tR\x12requestorSignature\x12\x14\n\x05nonce\x18\x07\x20\x01(\tR\
    \x05nonce\x12%\n\x0erequesting_org\x18\x08\x20\x01(\tR\rrequestingOrg2\
    \xed\x01\n\x07Network\x12B\n\x0cRequestState\x12\x1f.networks.networks.N\
    etworkQuery\x1a\x0f.common.ack.Ack\"\0\x12L\n\x08GetState\x12\".networks\
    .networks.GetStateMessage\x1a\x1a.common.state.RequestState\"\0\x12P\n\
    \x0fRequestDatabase\x12\x19.networks.networks.DbName\x1a\x20.networks.ne\
    tworks.RelayDatabase\"\0Bx\n#com.weaver.protos.networks.networksZQgithub\
    .com/hyperledger-labs/weaver-dlt-interoperability/common/protos-go/netwo\
    rksb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
